

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      # Mounts the project directory, allowing for hot-reloading
      - ./frontend:/app
      # Prevents the local node_modules from overwriting the container's
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
