name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ] # Triggers on push to these branches
  pull_request:
    branches: [ "master", "main" ] # Triggers on pull requests to these branches

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Backend Steps ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install httpx # Install testing dependency

      - name: Run backend tests
        run: pytest backend/tests

      # --- Frontend Steps ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Run frontend tests
        run: npm test --prefix frontend -- --watchAll=false

      # --- Build Docker Images (Optional CD Step) ---
      # This part is for Continuous Deployment.
      # It builds the images but doesn't push them yet.
      - name: Build Docker images
        run: |
          docker-compose build